[package]
name = "emos"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.11.0"




[[bin]]
name = "emos"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"