[build]
target = "x86_64-emos.json"

[target.x86_64-emos.json]
linker = "rust-lld"


[target.x86_64-emos]
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
