[build]
target = "x86_64-emos.json"

[target.x86_64-emos.json]
linker = "rust-lld"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
bindeps = true



[target.'cfg(target_os = "none")']
runner = "bootimage runner"
